export default {
  XBT: require('src/icons/XBT.png'),
  USDT: require('src/icons/USDT.png'),
  XRP: require('src/icons/XRP.png'),
  XLM: require('src/icons/XLM.png'),
  LTC: require('src/icons/LTC.png'),
  XDG: require('src/icons/XDG.png'),
  DASH: require('src/icons/DASH.png'),
  ETH: require('src/icons/ETH.png'),
  REP: require('src/icons/REP.png'),
  ZEC: require('src/icons/ZEC.png'),
  MLN: require('src/icons/MLN.png'),
  XMR: require('src/icons/XMR.png'),
  GNO: require('src/icons/GNO.png'),
  EOS: require('src/icons/EOS.png'),
  BCH: require('src/icons/BCH.png'),
  BSV: require('src/icons/BSV.png'),
  QTUM: require('src/icons/QTUM.png'),
  ADA: require('src/icons/ADA.png'),
  XTZ: require('src/icons/XTZ.png'),
  ETC: require('src/icons/ETC.png'),
  logo: require('src/icons/logo.png')
};
